# Generated by Django 5.1.5 on 2025-03-06 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examen", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="localidad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productos",
                to="examen.localidad",
            ),
        ),
    ]
