# Generated by Django 5.1.5 on 2025-03-06 23:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examen", "0002_alter_producto_localidad"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="fecha_creacion",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
