# Generated by Django 5.1.5 on 2025-03-06 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examen", "0003_producto_fecha_creacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="localidad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="examen.localidad"
            ),
        ),
    ]
