# Generated by Django 5.1.5 on 2025-02-13 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=500)),
                ("age", models.IntegerField()),
                ("rfc", models.CharField(max_length=500)),
                ("photo", models.URLField(max_length=1000, null=True)),
                ("created_date", models.DateTimeField(verbose_name="date created")),
                ("updated_date", models.DateTimeField(verbose_name="date updated")),
            ],
        ),
        migrations.CreateModel(
            name="Users_adress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(max_length=500)),
                ("zip_code", models.IntegerField()),
                ("city", models.CharField(max_length=200)),
                ("country", models.CharField(max_length=200)),
                ("created_date", models.DateTimeField(verbose_name="date created")),
                ("updated_date", models.DateTimeField(verbose_name="date updated")),
                (
                    "users_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.users"
                    ),
                ),
            ],
        ),
    ]
